### ISSUE TITLE
(2342) check Failed! Responese doesn't match eq3OK

### ISSUE THREAD

**Issue by Zaunkonig1** [Schnup89/ioBroker.eq3-Thermostat#14]
Hallo,

ich habe den Adapter installiert. 
Allerdings kann ich, so vermute ich, vom ioBroker aus nicht auf die Datei eq3Controller.py zugreifen.
Im Terminal funzt der Zugriff und ich bekommen ein "eq3OK" zurück.

Beim Test des Pfades im ioBroker erhalte ich in der Log folgende Fehlermeldung:
`

eq3-thermostat.0 | 2021-01-03 19:41:59.909 | info | ImportError: No module named 'eq3bt'
-- | -- | -- | --
eq3-thermostat.0 | 2021-01-03 19:41:59.909 | info | from eq3bt import Thermostat
eq3-thermostat.0 | 2021-01-03 19:41:59.909 | info | File "./home/pi/eq3Controller.py", line 1, in <module>
eq3-thermostat.0 | 2021-01-03 19:41:59.909 | info | Traceback (most recent call last):
eq3-thermostat.0 | 2021-01-03 19:41:59.909 | info | (2342) check Failed! Responese: Error: Command failed: python3 ./home/pi/eq3Controller.py check
eq3-thermostat.0 | 2021-01-03 19:41:59.907 | info | (2342) check Failed! Responese doesn't match eq3OK

`

Kann mir bitte jemand sagen, ob ich noch irgendwelche Berechtigungen setzen muß?

Das Script liegt im Verzeichnis /Home/pi.

Vielen Dank für die Unterstützung.

Gruß Matthias

**Comment by Schnup89** [comment]
Versuche es mal ohne den . vor dem ersten / im pfad (in der pfad variable auf der konfig-seite)

**Comment by Zaunkonig1** [comment]
Servus Schnup89,

leider das selbe in grün.


eq3-thermostat.0 | 2021-01-04 10:39:16.472 | info | ImportError: No module named 'eq3bt'
-- | -- | -- | --
eq3-thermostat.0 | 2021-01-04 10:39:16.472 | info | from eq3bt import Thermostat
eq3-thermostat.0 | 2021-01-04 10:39:16.472 | info | File "/home/pi/eq3Controller.py", line 1, in <module>
eq3-thermostat.0 | 2021-01-04 10:39:16.472 | info | Traceback (most recent call last):
eq3-thermostat.0 | 2021-01-04 10:39:16.472 | info | (31079) check Failed! Responese: Error: Command failed: python3 /home/pi/eq3Controller.py check
eq3-thermostat.0 | 2021-01-04 10:39:16.469 | info | (31079) check Failed! Responese doesn't match eq3OK

Die Fehlermeldung nach der Intervall-Überprüfung lautet:

eq3-thermostat.0 | 2021-01-04 10:41:24.950 | error | (31079) -----------"Error: Command failed: python3 /home/pi/eq3Controller.py getValue 00:1A:22:17:02:F8 Traceback (most recent call last):   File "/home/pi/eq3Controller.py", line 1, in <module>     f
-- | -- | -- | --
eq3-thermostat.0 | 2021-01-04 10:41:24.947 | error | (31079) Command "python3 /home/pi/eq3Controller.py getValue 00:1A:22:17:02:F8" failed!


Vielleicht bringt diese Info a bisserl Licht ins dunkle. ;-)


Gruß Matthias

**Comment by Schnup89** [comment]
Siehe issue #3, dort wurde das selbe Problem besprochen.
Die Library wird unter dem iobrokernicht gefunden.
Evtl. Hilft das kommando in der Konsole:

pip3 install --user iobroker python-eq3bt

**Comment by HugoChristian25** [comment]
Servus Schnup89,

ich habe leider das gleiche Problem wie Matthias. Bei der von dir vorgeschlagenen Lösung bekomme ich folgenden Fehler

`Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/iobroker/`
Weißt du woran das liegen könnte ?

Gruß,
Hugo

**Comment by Zaunkonig1** [comment]
Servus Schnup89,

vielen Dank für deine Antwort, aber beim ausführen dieses Befehles bekomme ich die folgende Fehlermeldung:

```
Could not find a version that satisfies the requirement iobroker (from versions: )
No matching distribution found for iobroker
```
Anschließend habe ich noch ein apt update und ein apt upgrade gemacht.
Abschließend noch ein iobroker fix

Beides brachte nicht den gewünschten Erfolg, sondern leider die gleiche Fehlermeldung.

Wenn ich den Befehl 'python3 /home/pi/eq3Controller.py getValue 00:1A:22:17:XX:XX' direkt in der SSH-Konsole ausführe,
bekomme ich eine Rückmeldung mit Werten (16.0;25;False).

Aber wenn ich den gleichen Befehl im Terminal direkt im ioBroker ausführe bekomme ich diese Fehlermeldung:
`Traceback (most recent call last):
   File "/home/pi/eq3Controller.py", line 1, in <module>
     from eq3bt import Thermostat
ImportError: No module named 'eq3bt'`


Vielen Dank für deine Unterstützung.


Gruß Matthias

**Comment by fh-kriftel** [comment]
Die Idee von Schnup89, dass es an den Rechten liegt, ist, denke ich korrekt. 
Ggf. sollte das Modul als iobroker user installieren:

sudo -H -u iobroker pip3 install python-eq3bt

**Comment by Zaunkonig1** [comment]
Servus fh-kriftel,

**das wars !!!!!**

Mit diesem Befehl hat es gefunzt. Nun funzt auch der Adapter.


Vielen Dank für Deine bzw. Eure Unterstützung.


Gruß Matthias

**Comment by Schnup89** [comment]
Danke fh-kruftel.
Lösung: sudo -H -u iobroker pip3 install python-eq3bt

**Comment by fh-kriftel** [comment]
Perfekt. Hat bei mir auch geklappt. 
Was mir noch aufgefallen ist - wenn man die Geräte nur ausliest, also keine Werte setzt, Dann scheinen sie im Automatikmodus zu bleiben. Ggf. ist das für den einen oder anderen interessant. Ich z.B. würde den Adapter erst einmal nur nutzen, um Temperatur und Batteriestatus auszulesen. Die Geräte haben nämlich die unschöne Eigenschaft, dass die Batterie i.d.R. im Status "Ventil offen" stirbt... Wenn das so ist, ggf. auch in der Doku ergänzen.

**Comment by Schnup89** [comment]
Danke für die Info, aber Vorsicht mit dem Modus.

Ich setze in dem Python-Script den Modus auf Manual sobald der Thermostat im Mode "Closed" ist.
Das war ein Workaround, weiß aber nicht mehr wofür... :/

`if sys.argv[1] == "getValue":   #Get Informatioms from BTDevice
        thermostat = Thermostat(sys.argv[2])
        thermostat.update()
        if str(thermostat.mode) == "Mode.Closed":
            thermostat.mode = 3   #Set Mode Manual
            thermostat.update()
        print(str(thermostat.target_temperature) + ";" + str(thermostat.valve_state)  + ";" + str(thermostat.low_battery))
        time.sleep(1)`
