### ISSUE TITLE
Noob hat  Problem bei Adapterinstallation des eq3

### ISSUE THREAD

**Issue by stevensen07** [Schnup89/ioBroker.eq3-Thermostat#2]
Hallo,
ich bin Elektroniker und hab mit Arduino etc rumgebastelt aber ich hab die Tage erst mit dem Raspberry und iobroker angefangen.
iobroker läuft und das Thermos eq3 hab ich gestern angebaut.
Wie im Github beschrieben habe ich schon geschafft mein Raspberry  mit dem  Thermstat zu koppeln und kann auch die Temperatur  per eq3Controller.py setzten. Und da bin ich schon begeistert!
 
Aber irgend wie bekomme ich das mit dem Adapter nicht hin. Folgende Fehler bzw. Warnungen (und bedenken Noob in Sachen Rasperry und iobroker) :

root@raspberrypi:/home/pi# npm i iobroker.eq3-thermostat
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

+ iobroker.eq3-thermostat@0.0.2
updated 1 package and audited 466 packages in 19.143s

8 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Was läuft da falsch? Könnt ihr/du mir helfen?
 Beste Grüße

**Comment by Schnup89** [comment]
Hi noob,

versuche den Adapter über das Webinterface zu installierem, das sollte dann klappen:

Adpater -> github icon oben klicken
Register "Beliebig" auswählen und die URL dieses Repository reinschreiben.


Viele Grüße

**Comment by stevensen07** [comment]
Hi Schnup89,

vielen Dank für die Antwort.
Ich habe versucht wie von Dir beschrieben den Adapter zu installieren. Dann
endete der Vorgang wie unten zu sehen:

$ ./iobroker url "https://github.com/Schnup89/ioBroker.eq3-Thermostat" --debug
install https://github.com/Schnup89/ioBroker.eq3-Thermostat/tarball/05467b2a0cbeea5c0093eba3c1b98ca9ff2d53bc
NPM version: 6.14.6
npm install https://github.com/Schnup89/ioBroker.eq3-Thermostat/tarball/05467b2a0cbeea5c0093eba3c1b98ca9ff2d53bc --loglevel error --prefix "/opt/iobroker" (System call)
+ iobroker.eq3-thermostat@0.0.2updated 1 package in 18.258s
24 packages are looking for funding  run `npm fund` for details
ERROR: host.raspberrypi Cannot install https://github.com/Schnup89/ioBroker.eq3-Thermostat/tarball/05467b2a0cbeea5c0093eba3c1b98ca9ff2d53bc: 0
ERROR: process exited with code 25

Was bedeutet das ?

**Comment by stevensen07** [comment]
Hat was gedauert irgenwann habe ich den Adapter gefunden und jetzt gehts wohl
Danke für die Hilfe.

**Comment by Schnup89** [comment]
Gerne
