### ISSUE TITLE
ModuleNotFoundError: No module named 'eq3bt'

### ISSUE THREAD

**Issue by JulianChristopher** [Schnup89/ioBroker.eq3-Thermostat#3]
Ich bekomme den Fehler. in der Console funktioniert es aber. 
da bekomme ich -->(30.0;100;False).
Ich habe bisher nichts mit python-skripten gemacht. 
Aber iobroker sollte die Rechte am Skript haben.
Was ich der beste Workaround in dem Fall?
Vielen Dank!
###############################################

eq3-thermostat.0 | 2020-09-27 13:30:02.632 | error | ModuleNotFoundError: No module named 'eq3bt'
-- | -- | -- | --
eq3-thermostat.0 | 2020-09-27 13:30:02.632 | error | from eq3bt import Thermostat
eq3-thermostat.0 | 2020-09-27 13:30:02.632 | error | File "/home/pi/eq3Controller.py", line 1, in <module>
eq3-thermostat.0 | 2020-09-27 13:30:02.632 | error | Traceback (most recent call last):
eq3-thermostat.0 | 2020-09-27 13:30:02.632 | error | (22571) -----------"Error: Command failed: python3 /home/pi/eq3Controller.py getValue 00:1A:22:0E:XX:XX
eq3-thermostat.0 | 2020-09-27 13:30:02.631 | error | (22571) Command "python3 /home/pi/eq3Controller.py getValue 00:1A:22:0E:xx:xx"

###############################################

eq3-thermostat.0 | 2020-09-27 14:40:02.666 | error | (22571) -----------"Error: Command failed: python3 /home/pi/eq3Controller.py getValue 00:1A:22:0E:xx:xx Traceback (most recent call last): File "/home/pi/eq3Controller.py", line 1, in <module> f
-- | -- | -- | --
eq3-thermostat.0 | 2020-09-27 14:40:02.664 | error | (22571) Command "python3 /home/pi/eq3Controller.py getValue 00:1A:22:0E:xx:xx" failed!
eq3-thermostat.0 | 2020-09-27 14:35:02.662 | error | (22571) -----------"Error: Command failed: python3 /home/pi/eq3Controller.py getValue 00:1A:22:0E:xx:xx Traceback (most recent call last): File "/home/pi/eq3Controller.py", line 1, in <module> f
eq3-thermostat.0 | 2020-09-27 14:35:02.659 | error | (22571) Command "python3 /home/pi/eq3Controller.py getValue 00:1A:22:0E:xx:xx" failed!

**Comment by Schnup89** [comment]
Hi JulianChristopher,

hast du auf der Console auch python3 benutzt?
**python3** /home/pi/eq3Controller.py getValue 00:1A:22:0E:XX:XX

PS: Habe deinen Beitrag editiert und die vier letzten MAC-Stellen entfernt :)

**Comment by JulianChristopher** [comment]
Super, danke da hatte ich wohl noch eine übersehen. ^^ Ja in der Console verwende ich auch den python 3. Auch mit pip3 installiert und das Paket ist auch im python 3 Ordner.

**Comment by Schnup89** [comment]
Kopiere das script mal nach /tmp:

cp /home/pi/eq3Controller.py /tmp/eq3Controller.py
und passe den Pfad in IOBroker an, damit sollten wir Berechtigungsprobleme ausschließen.

**Comment by JulianChristopher** [comment]
Das bekomme ich jetzt:

eq3-thermostat.0 | 2020-09-28 19:04:30.686 | error | ModuleNotFoundError: No module named 'eq3bt'
-- | -- | -- | --
eq3-thermostat.0 | 2020-09-28 19:04:30.686 | error | from eq3bt import Thermostat
eq3-thermostat.0 | 2020-09-28 19:04:30.686 | error | File "/tmp/eq3Controller.py", line 1, in <module>
eq3-thermostat.0 | 2020-09-28 19:04:30.686 | error | Traceback (most recent call last):
eq3-thermostat.0 | 2020-09-28 19:04:30.686 | error | (1672) -----------"Error: Command failed: python3 /tmp/eq3Controller.py getValue 00:1A:22:0E:xx:xx
eq3-thermostat.0 | 2020-09-28 19:04:30.685 | error | (1672) Command "python3 /tmp/eq3Controller.py getValue 00:1A:22:0E:xx:xx" failed!
eq3-thermostat.0 | 2020-09-28 19:04:30.634 | info | (1672) ##### RUN ADAPTER #####
eq3-thermostat.0 | 2020-09-28 19:04:30.632 | info | (1672) ##### CREATE OBJECTS #####
eq3-thermostat.0 | 2020-09-28 19:04:30.632 | info | (1672) PY-Script Path: "python3 /tmp/eq3Controller.py"
eq3-thermostat.0 | 2020-09-28 19:04:30.631 | info | (1672) Update-Interval: 5
eq3-thermostat.0 | 2020-09-28 19:04:30.631 | info | (1672) Loaded 1 eq3-Devices
eq3-thermostat.0 | 2020-09-28 19:04:30.631 | info | (1672) Update-Interval overwritten to: 5
eq3-thermostat.0 | 2020-09-28 19:04:30.630 | info | (1672) ##### LOAD CONFIG #####
eq3-thermostat.0 | 2020-09-28 19:04:30.630 | info | (1672) NODE Version = v10.22.1, we need new execSync
eq3-thermostat.0 | 2020-09-28 19:04:30.600 | info | (1672) starting. Version 0.0.2 in /opt/iobroker/node_modules/iobroker.eq3-thermostat, node: v10.22.1, js-controller: 3.1.6
host.raspberrypi | 2020-09-28 19:04:29.451 | info | instance system.adapter.eq3-thermostat.0 started with pid 1672
host.raspberrypi | 2020-09-28 19:04:26.961 | info | instance system.adapter.eq3-thermostat.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
eq3-thermostat.0 | 2020-09-28 19:04:26.441 | info | (1655) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
eq3-thermostat.0 | 2020-09-28 19:04:26.440 | info | (1655) terminating
eq3-thermostat.0 | 2020-09-28 19:04:26.439 | info | (1655) cleaned everything up...
eq3-thermostat.0 | 2020-09-28 19:04:26.435 | info | (1655) Got terminate signal TERMINATE_YOURSELF
host.raspberrypi | 2020-09-28 19:04:26.429 | info | stopInstance system.adapter.eq3-thermostat.0 send kill signal
host.raspberrypi | 2020-09-28 19:04:26.426 | info | stopInstance system.adapter.eq3-thermostat.0 (force=false, process=true)

**Comment by derherrgraf** [comment]
Ich kann den Fehler genau so reproduzieren. Ich hab mal aus Spaß an der Freunde in der Konsole das ganze mit `python eq3Controller.py` versucht laufen zu lassen und dann kommt auch in der Konsole 
```
Traceback (most recent call last):
  File "eq3Controller.py", line 1, in <module>
    from eq3bt import Thermostat
ImportError: No module named eq3bt
```

**Comment by Schnup89** [comment]
> Ich kann den Fehler genau so reproduzieren. Ich hab mal aus Spaß an der Freunde in der Konsole das ganze mit `python eq3Controller.py` versucht laufen zu lassen und dann kommt auch in der Konsole 
> ```
> Traceback (most recent call last):
>   File "eq3Controller.py", line 1, in <module>
>     from eq3bt import Thermostat
> ImportError: No module named eq3bt
> ```
> 
> Ich kopier jetzt mal keine Logs hier rein, da sie identisch sind (außer uhrzeit und macs)

Hi, wenn es in der Konsole schon eine Fehlermeldung gibt schau mal hier vorbei und befolge die Installation oder schau mal bei den issues.

https://github.com/rytilahti/python-eq3bt

**Comment by derherrgraf** [comment]
> Hi, wenn es in der Konsole schon eine Fehlermeldung gibt schau mal hier vorbei und befolge die Installation oder schau mal bei den issues.
> 
> https://github.com/rytilahti/python-eq3bt

Ich glaube das ist ein Missverständnis. Ich habe es erst mit python3 versucht über die Konsole, das hat wie @JulianChristopher bereits geschrieben hat fehlerfrei funktioniert. Dann hab ich es nochmal mit der anderen python version versucht, was dann auch auf der Konsole zu der Fehlermeldung führt.

=> Daher ist meine Vermutung dass der Adapter python verwenden obwohl python3 spezifiziert ist.

**Comment by derherrgraf** [comment]
So ich hab nochmal bisl rum gesucht. Es schein ein pip3 Problem zu sein `pip3 list` auf der Konsole liefert
```
Package        Version  
-------------- ---------
asn1crypto     0.24.0   
bluepy         1.3.0    
certifi        2018.8.24
chardet        3.0.4    
click          7.1.2    
click-datetime 0.2      
construct      2.10.56  
cryptography   2.6.1    
entrypoints    0.3      
idna           2.6      
keyring        17.1.1   
keyrings.alt   3.1.1    
pip            18.1     
pycrypto       2.6.1    
PyGObject      3.30.4   
python-apt     1.8.4.1  
** python-eq3bt   0.1.11 **   
pyxdg          0.25     
requests       2.21.0   
SecretStorage  2.3.1    
setuptools     40.8.0   
six            1.12.0   
ssh-import-id  5.7      
urllib3        1.24.1   
wheel          0.32.3   
```
wenn ich das ganze in der js console von io broker laufen lasse bekomme ich diese liste:
```
asn1crypto 0.24.0
certifi 2018.8.24
chardet 3.0.4
cryptography 2.6.1
entrypoints 0.3
idna 2.6
keyring 17.1.1
keyrings.alt 3.1.1
pip 18.1
pycrypto 2.6.1
PyGObject 3.30.4
python-apt 1.8.4.1
pyxdg 0.25
requests 2.21.0
SecretStorage 2.3.1
setuptools 40.8.0
six 1.12.0
ssh-import-id 5.7
urllib3 1.24.1
wheel 0.32.3
```
da fehlt das `python-eq3bt`modul

**Comment by Schnup89** [comment]
Ein Versuch wäre noch:

install pip3 --user iobroker python-eq3bt

**Comment by derherrgraf** [comment]
Ich hab das pip3 install über ein js exec laufen lassen und jetzt geht es. Wahrscheinlich muss es wirklich für den iobroker user extra installiert werden.

**Comment by Schnup89** [comment]
install pip3 --user iobroker python-eq3bt

Damit sollte das Problem behoben sein
