### ISSUE TITLE
No valid JSON for MAC: xxx

### ISSUE THREAD

**Issue by DJTechMo** [Schnup89/ioBroker.eq3-thermostat#31]
Moin,
wenn ich das neue Update installiere und mein Thermostat hinzufüge, kommt es zum Fehler: No valid JSON for MAC: xxxxx(MAC-Adressee)

**To Reproduce**  
Update installieren. 
Thermostat eintragen.
Adapter starten.

**Versions:**  
 - Adapter version: 2.0.1
 - JS-Controller version: 3.3.18
 - Node version: 12.18.3
 - Operating system: Debian 9

Log:
`
eq3-thermostat.0 | 2021-10-16 15:41:52.664 | error | No valid JSON for MAC: 00:1A:22:16:25:15

eq3-thermostat.0 | 2021-10-16 15:41:52.606 | error | No valid JSON for MAC: 00:1A:22:16:2F:2A

eq3-thermostat.0 | 2021-10-16 15:41:52.541 | info | ##### RUN ADAPTER #####

eq3-thermostat.0 | 2021-10-16 15:41:52.388 | info | ##### CREATE OBJECTS #####

eq3-thermostat.0 | 2021-10-16 15:41:52.387 | info | PY-Script Path: "expect /opt/iobroker/node_modules/iobroker.eq3-thermostat/eq3.exp"

eq3-thermostat.0 | 2021-10-16 15:41:52.386 | info | Button step: 1

eq3-thermostat.0 | 2021-10-16 15:41:52.385 | info | Update-Interval: 2

eq3-thermostat.0 | 2021-10-16 15:41:52.384 | info | Loaded 2 eq3-Devices

eq3-thermostat.0 | 2021-10-16 15:41:52.383 | info | Force Mode-Manual: false

eq3-thermostat.0 | 2021-10-16 15:41:52.382 | info | Button step overwritten to: 1

eq3-thermostat.0 | 2021-10-16 15:41:52.380 | info | ##### LOAD CONFIG #####
`

**Comment by Schnup89** [comment]
Servus,

habe ganze vergessen den JSON Output als debug log einzupflegen damit wir auch sehen was passiert.
Habe es in der Version 2.0.3 ergänzt, einfach den Adapter nochmal "drüber installieren" und mal den debug output anschauen.
Dort sollte dann folgende Nachrichten erscheinen:
error | No valid JSON for MAC: 00:1A:22:16:25:15
debug | error Message: *Fehlermeldung*
debug | Expect-Output: *Output von Expect-Script*

**Comment by Schnup89** [comment]
![image](https://user-images.githubusercontent.com/28166743/137590558-85c5b133-97d3-47d9-a2f7-432a6341bef3.png)

Hier nicht vergessen den debug zu aktivieren mit der version 2.0.3

**Comment by DJTechMo** [comment]
Jetzt bekomme ich:
Connection Error for MAC: xxx 
und nichts weiteres trotz Silly Logging
Pfad check ist aber successfull

**Comment by DJTechMo** [comment]
Restart hat es wohl gebracht. Das eine Thermostat ist wohl manchmal ausser Reichweite. Das zweite funktioniert.
Danke. Schauen wir mal wie stabil es so läuft.

**Comment by Schnup89** [comment]
Hallo Heini,

hast du den Debug modus in den Instanzeinstellungen aktiviert?
Damit sollten wir eine zusätzliche Fehlermeldung im loglevel "Debug" bekommen.

Alternativ auf der console bitte folgenden Befehl testen und den Output hierher kopieren:
expect  /opt/iobroker/node_modules/iobroker.eq3-thermostat/eq3.exp *mac* json
