### ISSUE TITLE
Instanz fehlt

### ISSUE THREAD

**Issue by pixSR** [Schnup89/ioBroker.eq3-thermostat#32]
Nachdem ich nun deinen neuen Link verwendet habe
https://github.com/Schnup89/ioBroker.eq3-thermostat
ist die Installation scheinbar auch ohne Fehlermeldung durchgelaufen.
Ich habe nun allerdings das Problem dass der Adapter installiert ist, ich aber keine Config öffnen kann, da nichts unter den Instanzen dargestellt wird.
In den Objekten des iobroker ist der Baum für eq3-thermostat enthalten und hat noch einen Unterordner für Admin erhalten mit Inhalt {
  "type": "meta",
  "common": {
    "name": "admin",
    "type": "admin"
  },
  "from": "system.host.raspberrypi.cli",
  "ts": 1634401083311,
  "native": {},
  "_id": "eq3-thermostat.admin",
  "acl": {
    "object": 1638,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
Benötigt dein Adapter noch mehr Funktionen im iobroker - dieser wurde kurz zuvor frisch aufgesetzt.

**Comment by Schnup89** [comment]
Wenn unter Instanz keine erstellt wurde, dann musst diese hinzufügen:
![image](https://user-images.githubusercontent.com/28166743/137597698-364cfe25-b1bd-4954-a936-f992267368ec.png)
Hier ... auswählen
![image](https://user-images.githubusercontent.com/28166743/137597706-068ce3bc-c142-4f5e-9e3e-2ddad602c510.png)
links unten auf +
