### ISSUE TITLE
Boost Button as State

### ISSUE THREAD

**Issue by andri-anski** [Schnup89/ioBroker.eq3-thermostat#33]
Super Arbeit, Vielen Dank!
Wäre es möglich die Boost-Funktion hinzuzufügen, die durch den eq3.exp Script unterstützt wird.
Das wäre schön.

**Comment by Schnup89** [comment]
https://github.com/Schnup89/ioBroker.eq3-thermostat/commit/4c5a702b9421aca489470a06f158ed182885951e
