### ISSUE TITLE
Wrong text in logs "PY-Script"

### ISSUE THREAD

**Issue by andri-anski** [Schnup89/ioBroker.eq3-thermostat#36]
Nach Umstellung auf sh-script sind im Log noch einige Überbleibsel der Python-Ära geblieben.
z.B. :
`PY-Script Path: "expect /opt/iobroker/node_modules/iobroker.eq3-thermostat/eq3.exp" `

**Comment by Schnup89** [comment]
Hab ich übersehen, danke für die Info!
https://github.com/Schnup89/ioBroker.eq3-thermostat/blob/7dbd50c578099a17058c388b0d88c406f3b9ab53/main.js
