### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [Schnup89/ioBroker.eq3-thermostat#45]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/Schnup89/ioBroker.eq3-thermostat

- [x] [E506] Word "lab_eq3Controller_path_long" is not translated to russian in admin/words.js. You can use https://translator.iobroker.in/ for translations
- [x] [E506] Word "text_devices" is not translated to russian in admin/words.js. You can use https://translator.iobroker.in/ for translations

I have also found warnings that may be fixed if possible.

- [x] [W400] Cannot find "eq3-thermostat" in latest repository

Thanks,
your automatic adapter checker.

P.S.: There is a community in Github, which supports the maintenance and further development of adapters. There you will find many experienced developers who are always ready to assist anyone. New developers are always welcome there. For more informations visit: https://github.com/iobroker-community-adapters/info

**Comment by Schnup89** [comment]
Close
