### ISSUE TITLE
Problem bei Adapter Installation

### ISSUE THREAD

**Issue by robertpfeifer2000** [Schnup89/ioBroker.eq3-Thermostat#5]
Hi
Ich hoffe das Anliegen ist hier richtig....
Habe heute versucht den Adapter zu installieren.
DIe Python Library zu installieren hat ohne Fehler funktioniert, allerdings bei der Installation des Adapters kam von ioBroker nach langen laden eine Fehlermeldung.
Ich kopiere einfach mal die komplette Ausgabe rein, und hoffe jemand kann den Fehler rauslesen, und mir weiterhelfen.
Schonmal danke im voraus.

https://pastebin.com/PdgiwVUX

**Comment by Schnup89** [comment]
Hey,

das scheint ein Problem mit dem Node-Modul "gyp" zu sein.
Davon hab ich bisher leider noch nicht gehört, aber eine kurze suche brachte mir folgenden Forumsthread:

https://forum.iobroker.net/topic/24316/gel%C3%B6st-adapterinstallation-node-gyp-error

Ich kann dir bei der Fehlermeldung leider nicht weiterhelfen da diese nur indirekt etwas mit dem Adapter zu tun hat.

**Comment by robertpfeifer2000** [comment]
Danke für die Antwort.
Nachdem der Adapter gestern Abend plötzlich auch unter den offiziellen Adaptern in ioBroker zu finden war ging die Installation komischerweise ohne Probleme von statten.
Ich hole mir heute mal ein Thermostat, und teste dann ob ich es zum laufen bekomme.

**Comment by robertpfeifer2000** [comment]
Falls du es in die Dokumentation o.ä. mit aufnehmen willst, die eqiva Bluetooth Thermostate (kosten ca 20€) funktionieren einwandfrei, steuerung und Übertragung der Temperatur läuft in beide Richtungen ohne Probleme

**Comment by Schnup89** [comment]
Vielen Dank für deine positive Rückmeldung! 
Für genau diese Thermostate ist der Adapter erstellt worden.
