### ISSUE TITLE
Mode Button and other Buttons as State 

### ISSUE THREAD

**Issue by Heini1985** [Schnup89/ioBroker.eq3-thermostat#52]
Hallo zusammen,

Erstmal ein Großes Danke an Schnup89 für diesen EQ3 Adapter der gut funktioniert. Aber mit fehlt ein paar Objekte im iObroker.

z.B. Wenn ich das Haus verlassen will ich das die Thermostate in den manuellen Mode gehen und die Temperatur auf 18°C bleibt und wenn ich wieder da bin sollen sie wieder ihr gespeichertes Programm abfahren. Ohne diese Option muss ich ihm immer wieder die Temperatur in bestimmten Intervallen setzen damit die Heizkörper nicht anfangen zu Heizen.

Ein Anderes Beispiel ist wenn es Sommer wird dann will ich die Thermostate auf 5°C stellen damit die nicht mehr Heizen solange draußen 18°C ist. einfach auf manuell und 5°C das währe alles. schont auch noch die Batterie

Mode als Objekt im iObroker ausführen das währe cool.

Oder gibt es schon diese Möglichkeit aber ich habe die nicht entdeckt.

Danke.

Gruß

Heini1985

**Comment by Heini1985** [comment]
Hi hier noch ein Nachtrag:

ich habe mit dem Befehl "expect /opt/iobroker/node_modules/iobroker.eq3-thermostat/eq3.exp 00:1A:22:XX:XX:XX auto/manual" rum gespielt es funktioniert wunderbar an meinem iobrokermaster aber ich kann das aus dem Blockly auf meinem iobrokerslave ausführen deswegen wollte ich den Button "Mode" oder "auto" haben.

P.S. wenn man schon dabei ist, könnte man auch die Optionen "Lock / Unlock" oder "off / on " auch als Objekt ausführen das währe für alle Benutzer deines Adapters eine super Sache.

Viele Grüße

Heini1985

**Comment by Schnup89** [comment]
Hi Heini,

danke für deine Vorarbeit bzgl. des auto/manual Befehl.
Ich schaue mir das an, habe aber aktuell kein Gerät zum testen da von daher muss ich da "ins Blaue" programmieren und hoffen dass es läuft...

**Comment by Schnup89** [comment]
https://github.com/Schnup89/ioBroker.eq3-thermostat/commit/aa064b26b1401cfd65d2f17de689f4bb83381a33

Habe mich an dem letzten Change gehalten, sollte so funktionieren.
Bitte beachte:
Manuellen Modus erzwingen muss aus sein wenn du den status (auto/manual) immer manuell setzen willst
on/off (Thermostat aus und an) habe ich nicht implementiert, das kann selbst mit dem temperature state realisiert werden (einfach die gewünschte temperatur setzen)

Gruß
Tobias

**Comment by Heini1985** [comment]
Danke ich probiere es aus.
 Befehl für off/on lautet: expect /opt/iobroker/node_modules/iobroker.eq3-thermostat/eq3.exp 00:1A:22:XX:XX:XX off/on
Befehl für locl /unlock lautet :expect /opt/iobroker/node_modules/iobroker.eq3-thermostat/eq3.exp 00:1A:22:XX:XX:XX lock/unlock

danke

**Comment by Heini1985** [comment]
Hallo Schnup89

Ich habe es grade getestet. Auto und lock funktionieren beide.

Danke das ist schon eine super.

**Comment by Schnup89** [comment]
https://github.com/Schnup89/ioBroker.eq3-thermostat/commit/9cec3bbbaaacedb320f104f5dafcd0cfc97f3ba1

ON/OFF habe ich noch schnell dazugewurschtelt :)

**Comment by Heini1985** [comment]
Hallo und danke, aber jetzt bekomme ich es nicht mehr installiert. folgende Fehlermeldung:

$ iobroker url https://github.com/Schnup89/ioBroker.eq3-thermostat --host iobrokermaster

install Schnup89/ioBroker.eq3-thermostat#9cec3bbbaaacedb320f104f5dafcd0cfc97f3ba1

NPM version: 8.5.0

Installing Schnup89/ioBroker.eq3-thermostat#9cec3bbbaaacedb320f104f5dafcd0cfc97f3ba1... (System call)

up to date in 24s98 packages are looking for funding run `npm fund` for details

Could not read io-package.json: /opt/iobroker/node_modules/iobroker.eq3-thermostat/io-package.json: Unexpected end of JSON input

upload [3] eq3-thermostat.admin /opt/iobroker/node_modules/iobroker.eq3-thermostat/admin/eq3-thermostat.png eq3-thermostat.png image/png

upload [2] eq3-thermostat.admin /opt/iobroker/node_modules/iobroker.eq3-thermostat/admin/index_m.html index_m.html text/html

upload [1] eq3-thermostat.admin /opt/iobroker/node_modules/iobroker.eq3-thermostat/admin/style.css style.css text/css

upload [0] eq3-thermostat.admin /opt/iobroker/node_modules/iobroker.eq3-thermostat/admin/words.js words.js application/javascript

Could not read io-package.json: /opt/iobroker/node_modules/iobroker.eq3-thermostat/io-package.json: Unexpected end of JSON input

Cannot parse /opt/iobroker/node_modules/iobroker.eq3-thermostat/io-package.json: /opt/iobroker/node_modules/iobroker.eq3-thermostat/io-package.json: Unexpected end of JSON inputCannot find io-package.json in /opt/iobroker/node_modules/iobroker.eq3-thermostat

Process exited with code 0

kannst du es beheben

**Comment by Schnup89** [comment]
Da hat sich der Fehlerteufel eingeschlichen, sollte wieder gehen

**Comment by Heini1985** [comment]
super klappt

**Comment by Heini1985** [comment]
ich teste es eben und gebe dir Rückmeldung

**Comment by Heini1985** [comment]
kleiner fehler in der Main.js

<html>
<body>


ReferenceError: bLocked is not defined at Eq3Thermostat.fSetON (/opt/iobroker/node_modules/iobroker.eq3-thermostat/main.js:429:42) at Eq3Thermostat.onStateChange (/opt/iobroker/node_modules/iobroker.eq3-thermostat/main.js:174:26) at Eq3Thermostat.emit (node:events:526:28) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5379:53) at processImmediate (node:internal/timers:466:21)
--



</body>
</html>

**Comment by Heini1985** [comment]
Hallo schnurp89

etwas funktioniert nicht richtig

er zeigt mir beim Host folgendes an:

<html>
<body>


host.iobrokermaster | 2022-04-25 00:05:36.098 | info | Do not restart adapter system.adapter.eq3-thermostat.0 because desired by instance
-- | -- | -- | --
host.iobrokermaster | 2022-04-25 00:05:36.097 | error | instance system.adapter.eq3-thermostat.0 terminated by request of the instance itself and will not be restarted, before user restarts it.


</body>
</html>

kannst du etwas damit anfangen den fehler von oben habe ich korregiert.

**Comment by Schnup89** [comment]
Habe noch einen Tippfehler gefunden und korrigiert, war wohl doch etwas spät... 
Sollte jetzt auch funktionieren

**Comment by Heini1985** [comment]
Nein funktioniert nicht immer noch der selbe Fehler

**Comment by Heini1985** [comment]
Danke Schnup89

Der Adapter funktioniert alles top.
ich schließe dieses Issue

War eine kurze Nacht :-)

Viele Grüße

Heini1985
