### ISSUE TITLE
Fehlermeldungen

### ISSUE THREAD

**Issue by robertpfeifer2000** [Schnup89/ioBroker.eq3-thermostat#7]
Hi, ich habe den Adapter schon seit ein paar Wochen erfolgreich am laufen.
Ein Problem was seit Anfang an besteht (dem ich aber nicht viel Beachtung geschenkt habe) sind folgende Fehlermeldungen im Log.

![Screenshot 2020-11-18 205504](https://user-images.githubusercontent.com/36845041/99580980-6f33a200-29e0-11eb-9f69-ae43f7e54558.png)

An sich funktioniert alles wie es soll....die Temperaturen lassen sich ohne größere Probleme einstellen (manchmal verstellen sich 2 der 3 Thermostate von selbst....ist aber seltener geworden).

Was haben diese Log-Einträge zu bedeuten?
Hat der ein Problem damit dass es 3 Thermostate auf einmal sind, dass die deswegen nicht erreichbar sind?

Vielen Danke, und MfG....Robert

**Comment by derherrgraf** [comment]
duplicate #6

**Comment by Schnup89** [comment]
Hi,
ich setze für die BT-Kommunikation mit den eq3's auf folgende Library (https://github.com/rytilahti/python-eq3bt).
Da das Errorhandling und das Verbindungshandling bei mehreren Verbindungen leider bei der Lib eingeschränkt ist, gibt es die erwähnten Fehlermeldungen.

Ein höherer Refresh-Intervall könnte hier Abhilfe schaffen, einfach mal testen.

Das Problem ist bekannt, um das zu lösen muss aber die Python-Library angepasst oder auf eine andere Python-Library gesetzt werden. Sobald ich wieder Zugriff einen Thermostat habe gehe ich das Thema an.

**Comment by Predator83** [comment]
Ich hab die Erfahrung gemacht, dass die Lib crasht wenn du gleichzeitig mehrere Verbindungen zum gleichen Thermostat aufbaust. Gleichzeitige Verbindungen zu unterschiedlichen Thermostaten waren kein Problem.

Wie geht die Lib/iobroker eigentlich damit um, wenn eine Anfrage an das Thermostat geschickt wird und keine Antwort kommt? Noch eine Anfrage schicken? Das könnte dann den Crash und die Fehlermeldungen erklären. 

Die Fehler im Log kenn ich auch zur Genüge ;-)

**Comment by ManuelW77** [comment]
Sollte so besser funktionieren: https://github.com/Schnup89/ioBroker.eq3-Thermostat/pull/16

**Comment by Schnup89** [comment]
Mit der neuen Version ist das Error-Handling verbessert, am besten testen und das Issue wieder öffnen wenn es noch Probleme gibt.
