### ISSUE TITLE
Add plus and minus button

### ISSUE THREAD

**Issue by derherrgraf** [Schnup89/ioBroker.eq3-Thermostat#9]
Add the buttons for better including in a vis. I do this now with an extra script but i want to add this to the adapter.

**Comment by derherrgraf** [comment]
@Schnup89 magst du mir das recht geben mich für issues eintragen zu können? Würde hier gerne etwas aktiver mit machen :)

**Comment by Schnup89** [comment]
Für Heidelberger mache ich das doch gerne :D

Einladung ist raus, da ich aber noch nicht so viel mit github gemacht habe, bin ich mir nicht sicher ob das passt.

Gruß aus dem Rhein-Pfalz-Kreis

**Comment by derherrgraf** [comment]
Ja das passt perfekt :) Außerdem bin ich Schwetzinger, daher sogar Grüße nur über den Fluß quasi :D
